version: "3.3"
services:
  api:
    container_name: api
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - mongo
    volumes:
      - /usr/src/app/node_modules
      - ../:/usr/src/app

    command: "bash -c 'wait && yarn run start-dev'"
    env_file: 'api.env'
    environment:
      WAIT_HOSTS: mongo:27017

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  postgres:
    container_name: postgres
    image: postgres
    restart: always
