FROM node:10.8.0

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn install

COPY . . 

EXPOSE 8080

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait